baseurl = "https://ausbiometric2019.org/"
title = "Biometrics by the Botanic Gardens"
theme = "hugo-universal-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


# To Do list
# Sponsors
#    - GRDC
#    - University of Adelaide
#    - SAHMRI
# Update Workshop details
# Contact for conference scientific Committee, (Petra)
# Put it on twitter (??)
#    - 
# Book of Abstracts only as pdf
# Programme table fixed first column
# Add dinner details and venue
# Page for social programme




languageCode = "en-au"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
# disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-123499055-4"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Registration & Key Dates"
    url  = "/registration/"
    weight = 2	

#[[menu.main]]
#    name = "Submit Abstract"
#    url  = "/abstract/"
#	weight = 3
	
[[menu.main]]
    name = "Speakers"
    url  = "/speakers/"
    weight = 3

[[menu.main]]
    name = "Programme"
    identifier = "prog"
    url  = "#"
    weight = 4
	
    [[menu.main]]
        name = "Programme Outline"
        url  = "/outline/"
        parent = "prog"
        weight = 2
        
    [[menu.main]]
        name = "Workshops"
        url  = "/workshops/"
        parent = "prog"
        weight = 2
        
    [[menu.main]]
        name = "Social Programme"
        url  = "/social/"
        parent = "prog"
        weight = 3
	
[[menu.main]]
    name = "Visiting Adelaide"
    identifier = "tourism"
    url  = "#"
    weight = 5
	
	[[menu.main]]
        name = "Travel"
        url  = "/travel/"
        parent = "tourism"
        weight = 1
        
    [[menu.main]]
        name = "Accomodation"
        url  = "/accomodation/"
        parent = "tourism"
        weight = 2      
        
    [[menu.main]]
        name = "Things to do"
        url  = "/tourism/"
        parent = "tourism"
        weight = 2
        
    [[menu.main]]
        name = "About the Venue"
        url  = "/venue/"
        parent = "tourism"
        weight = 4

	
#[[menu.main]]
#    name = "Sponsors"
#    identifier = "sponsors"
#    url  = "/sponsors/"
#    weight = 7

#[[menu.main]]
#    name = "Contact"
#    url  = "/contact/"
#    weight = 8

	
[[menu.main]]
    name = "About"
    identifier = "about"
    url  = "#"
    weight = 8
	
    [[menu.main]]
        name = "Contact"
        url  = "/contact/"
        parent = "about"
        weight = 2
        
    [[menu.main]]
        name = "Code of Conduct"
        url  = "/conduct/"
        parent = "about"
        weight = 3
        
    [[menu.main]]
        name = "Conditions of Registration"
        url  = "/conditions/"
        parent = "about"
        weight = 4
        
        

[params]
    viewMorePostLink = "/post/"
    author = "The Biometry Hub"
    defaultKeywords = ["conference", "statistics", "biometrics", "biometry"]
    #defaultDescription = "Site template made by devcows using hugo"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "green"

		
	
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "ausbiometric2019@adelaide.edu.au"

    about_us = "Website is currently under construction. Please check back soon for more details! If you require further information, please use the [contact form](/contact). The full list of people who made this conference happen can be found [here](/acknowledgements/)."
    copyright = "&copy; 2019, [The Biometry Hub](https://biometryhubwaite.com), University of Adelaide; All rights reserved."
    
    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
	
    address = """<strong><a href="mailto:ausbiometric2019@adelaide.edu.au">Local Organising Committee</a></strong>, University of Adelaide<br><br>"""
    
    #"""<p><strong>The Biometry Hub</strong>
    #    <br>Level 2, Main Waite Building
    #    <br>Waite Road
    #    <br>Waite Campus
    #    <br>Urrbrae 5064
    #    <br>
    #    <strong>South Australia</strong>
    #  </p>
    #  """
      
    scicom = """<strong><a href="mailto:Petra.Kuhnert@data61.csiro.au">Dr Petra Kuhnert</a></strong>, Chair of scientific committee"""  
      
    orgcom = """<strong><a href="mailto:Alan.Welsh@anu.edu.au">Prof Alan Welsh</a></strong>, Chair of conference organising committee 
	    <br><strong><a href="mailto:Petra.Kuhnert@data61.csiro.au">Dr Petra Kuhnert</a></strong>, Chair of scientific committee
        <br><strong><a href="mailto:olena.kravchuk@adelaide.edu.au">Dr Olena Kravchuk</a></strong>, Chair of local organising committee
        <br><strong><a href="mailto:warren.muller@csiro.au">Mr Warren Muller</a></strong>, Treasurer
      """
      
	# Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyAEWfK0x75ZQTAxRdqp7oNQxVSZ4FEG0gI"
  
    latitude = "-34.919619" 
    longitude = "138.613999"
	direction = "National Wine Centre, Adelaide SA"

[Permalinks]
    blog = "/post/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
#[params.topbar]
#    enable = false
#    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
#      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
#      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
#      </p>
#      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = false
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Invited Speakers"
    subtitle = ""

[params.see_more]
    enable = false
#    icon = "fa fa-file-code-o"
#    title = ""
#    subtitle = ""
    link_url = "https://www.thewaite.org"
   link_text = "The Waite Campus"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Sponsors"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
